name: Daniel de Carvalho
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0289
title: A passion for communication
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f2'
    - '#d3cfd0'
    - '#d6aaa1'
    - '#363030'
    - '#9d7c73'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
