name: Daniel de Carvalho
favicon: null
layout_spectrum: 0.7407
typography_spectrum: 0.75832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f2'
    - '#d3cfd0'
    - '#d6aaa1'
    - '#363030'
    - '#9d7c73'
  brandStrength: 0.3363488628529012
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
