name: Daniel de Carvalho
favicon: null
layout_spectrum: 0.24951
typography_spectrum: 0.49022
title: A passion for communicaions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f2'
    - '#d3cfd0'
    - '#d6aaa1'
    - '#363030'
    - '#9d7c73'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
